services:
  backend:
    image: rimbourgou/fastia-backend:${APP_VERSION}
    ports:
      - "8000:8000"

  frontend:
    image: rimbourgou/fastia-frontend:${APP_VERSION}
    environment:
      - API_URL=http://backend:8000
    ports:
      - "8501:8501"
    depends_on:
      - backend
